/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SomeThing as PrismaSomeThing,
  Customer as PrismaCustomer,
} from "@prisma/client";

export class SomeThingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SomeThingCountArgs, "select">
  ): Promise<number> {
    return this.prisma.someThing.count(args);
  }

  async someThings(
    args: Prisma.SomeThingFindManyArgs
  ): Promise<PrismaSomeThing[]> {
    return this.prisma.someThing.findMany(args);
  }
  async someThing(
    args: Prisma.SomeThingFindUniqueArgs
  ): Promise<PrismaSomeThing | null> {
    return this.prisma.someThing.findUnique(args);
  }
  async createSomeThing(
    args: Prisma.SomeThingCreateArgs
  ): Promise<PrismaSomeThing> {
    return this.prisma.someThing.create(args);
  }
  async updateSomeThing(
    args: Prisma.SomeThingUpdateArgs
  ): Promise<PrismaSomeThing> {
    return this.prisma.someThing.update(args);
  }
  async deleteSomeThing(
    args: Prisma.SomeThingDeleteArgs
  ): Promise<PrismaSomeThing> {
    return this.prisma.someThing.delete(args);
  }

  async getCustomer(parentId: string): Promise<PrismaCustomer | null> {
    return this.prisma.someThing
      .findUnique({
        where: { id: parentId },
      })
      .customer();
  }
}
