/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { NewModel } from "./NewModel";
import { NewModelCountArgs } from "./NewModelCountArgs";
import { NewModelFindManyArgs } from "./NewModelFindManyArgs";
import { NewModelFindUniqueArgs } from "./NewModelFindUniqueArgs";
import { CreateNewModelArgs } from "./CreateNewModelArgs";
import { UpdateNewModelArgs } from "./UpdateNewModelArgs";
import { DeleteNewModelArgs } from "./DeleteNewModelArgs";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { NewModelService } from "../newModel.service";
@graphql.Resolver(() => NewModel)
export class NewModelResolverBase {
  constructor(protected readonly service: NewModelService) {}

  async _newModelsMeta(
    @graphql.Args() args: NewModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [NewModel])
  async newModels(
    @graphql.Args() args: NewModelFindManyArgs
  ): Promise<NewModel[]> {
    return this.service.newModels(args);
  }

  @graphql.Query(() => NewModel, { nullable: true })
  async newModel(
    @graphql.Args() args: NewModelFindUniqueArgs
  ): Promise<NewModel | null> {
    const result = await this.service.newModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NewModel)
  async createNewModel(
    @graphql.Args() args: CreateNewModelArgs
  ): Promise<NewModel> {
    return await this.service.createNewModel({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => NewModel)
  async updateNewModel(
    @graphql.Args() args: UpdateNewModelArgs
  ): Promise<NewModel | null> {
    try {
      return await this.service.updateNewModel({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => NewModel)
  async deleteNewModel(
    @graphql.Args() args: DeleteNewModelArgs
  ): Promise<NewModel | null> {
    try {
      return await this.service.deleteNewModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Product], { name: "products" })
  async findProducts(
    @graphql.Parent() parent: NewModel,
    @graphql.Args() args: ProductFindManyArgs
  ): Promise<Product[]> {
    const results = await this.service.findProducts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
