/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { NewModelService } from "../newModel.service";
import { NewModelCreateInput } from "./NewModelCreateInput";
import { NewModel } from "./NewModel";
import { NewModelFindManyArgs } from "./NewModelFindManyArgs";
import { NewModelWhereUniqueInput } from "./NewModelWhereUniqueInput";
import { NewModelUpdateInput } from "./NewModelUpdateInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

export class NewModelControllerBase {
  constructor(protected readonly service: NewModelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: NewModel })
  async createNewModel(
    @common.Body() data: NewModelCreateInput
  ): Promise<NewModel> {
    return await this.service.createNewModel({
      data: data,
      select: {
        createdAt: true,
        id: true,
        newFieldandOneWasRemoved: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [NewModel] })
  @ApiNestedQuery(NewModelFindManyArgs)
  async newModels(@common.Req() request: Request): Promise<NewModel[]> {
    const args = plainToClass(NewModelFindManyArgs, request.query);
    return this.service.newModels({
      ...args,
      select: {
        createdAt: true,
        id: true,
        newFieldandOneWasRemoved: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: NewModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async newModel(
    @common.Param() params: NewModelWhereUniqueInput
  ): Promise<NewModel | null> {
    const result = await this.service.newModel({
      where: params,
      select: {
        createdAt: true,
        id: true,
        newFieldandOneWasRemoved: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: NewModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateNewModel(
    @common.Param() params: NewModelWhereUniqueInput,
    @common.Body() data: NewModelUpdateInput
  ): Promise<NewModel | null> {
    try {
      return await this.service.updateNewModel({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          newFieldandOneWasRemoved: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: NewModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteNewModel(
    @common.Param() params: NewModelWhereUniqueInput
  ): Promise<NewModel | null> {
    try {
      return await this.service.deleteNewModel({
        where: params,
        select: {
          createdAt: true,
          id: true,
          newFieldandOneWasRemoved: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/products")
  @ApiNestedQuery(ProductFindManyArgs)
  async findProducts(
    @common.Req() request: Request,
    @common.Param() params: NewModelWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProducts(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        itemPrice: true,
        name: true,

        newModel: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/products")
  async connectProducts(
    @common.Param() params: NewModelWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        connect: body,
      },
    };
    await this.service.updateNewModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/products")
  async updateProducts(
    @common.Param() params: NewModelWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        set: body,
      },
    };
    await this.service.updateNewModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/products")
  async disconnectProducts(
    @common.Param() params: NewModelWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        disconnect: body,
      },
    };
    await this.service.updateNewModel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
