/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  NewModel as PrismaNewModel,
  Product as PrismaProduct,
} from "@prisma/client";

export class NewModelServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.NewModelCountArgs, "select">): Promise<number> {
    return this.prisma.newModel.count(args);
  }

  async newModels(
    args: Prisma.NewModelFindManyArgs
  ): Promise<PrismaNewModel[]> {
    return this.prisma.newModel.findMany(args);
  }
  async newModel(
    args: Prisma.NewModelFindUniqueArgs
  ): Promise<PrismaNewModel | null> {
    return this.prisma.newModel.findUnique(args);
  }
  async createNewModel(
    args: Prisma.NewModelCreateArgs
  ): Promise<PrismaNewModel> {
    return this.prisma.newModel.create(args);
  }
  async updateNewModel(
    args: Prisma.NewModelUpdateArgs
  ): Promise<PrismaNewModel> {
    return this.prisma.newModel.update(args);
  }
  async deleteNewModel(
    args: Prisma.NewModelDeleteArgs
  ): Promise<PrismaNewModel> {
    return this.prisma.newModel.delete(args);
  }

  async findProducts(
    parentId: string,
    args: Prisma.ProductFindManyArgs
  ): Promise<PrismaProduct[]> {
    return this.prisma.newModel
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .products(args);
  }
}
